const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const auth = require('../middleware/auth');

router.post('/career-report', auth, async (req, res) => {
    try {
        const { job, insights, interviewSummary } = req.body;
        
        const doc = new PDFDocument({ margin: 50 });
        
        // Header
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Career_Report_${job.company}.pdf`);
        
        doc.pipe(res);
        
        // Title
        doc.fillColor('#6366f1').fontSize(24).text('Career Roadmap', { align: 'center' });
        doc.moveDown(0.5);
        doc.fillColor('#94a3b8').fontSize(12).text(`Generated by JobTracker AI`, { align: 'center' });
        doc.moveDown(2);
        
        // Job Section
        doc.fillColor('#1e293b').fontSize(18).text(job.jobTitle, { continued: true });
        doc.fillColor('#64748b').fontSize(14).text(`  at ${job.company}`);
        doc.moveDown(0.5);
        if (job.location) doc.fontSize(10).fillColor('#94a3b8').text(`Location: ${job.location}`);
        doc.moveDown(1.5);
        
        // Horizontal Line
        doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#e2e8f0').stroke();
        doc.moveDown(1.5);
        
        // Resume Tips
        if (insights.resume && insights.resume.length > 0) {
            doc.fillColor('#1e293b').fontSize(16).text('Resume Optimization Tips');
            doc.moveDown(0.5);
            insights.resume.forEach(tip => {
                doc.fillColor('#475569').fontSize(11).text(`• ${tip}`, { indent: 20 });
                doc.moveDown(0.3);
            });
            doc.moveDown(1.5);
        }
        
        // Interview Questions
        if (insights.interview && insights.interview.length > 0) {
            doc.fillColor('#1e293b').fontSize(16).text('Key Interview Questions & Strategies');
            doc.moveDown(0.5);
            insights.interview.forEach((item, i) => {
                doc.fillColor('#1e293b').fontSize(11).text(`${i+1}. ${item.question}`, { indent: 10 });
                doc.fillColor('#64748b').fontSize(10).text(`Strategy: ${item.hint}`, { indent: 25 });
                doc.moveDown(0.5);
            });
            doc.moveDown(1.5);
        }
        
        // Email Draft
        if (insights.email) {
            doc.fillColor('#1e293b').fontSize(16).text('Follow-up Correspondence');
            doc.moveDown(0.8);
            
            const boxY = doc.y;
            const boxHeight = 160; // Slightly larger for better fit
            
            // Draw background box
            doc.rect(50, boxY, 500, boxHeight)
               .strokeColor('#e2e8f0')
               .fillAndStroke('#f8fafc', '#e2e8f0');
            
            // Text inside box
            doc.fillColor('#475569')
               .fontSize(10)
               .text(insights.email, 70, boxY + 15, { 
                   width: 460,
                   lineGap: 2
               });
            
            // Move cursor past the box
            doc.y = boxY + boxHeight + 20;
        }
        
        // Virtual Interview Feedback (If exists)
        if (interviewSummary) {
            doc.addPage();
            doc.fillColor('#1e293b').fontSize(18).text('Virtual Interview Performance Report');
            doc.moveDown(1);
            doc.fillColor('#475569').fontSize(11).text(interviewSummary);
        }
        
        doc.end();
        
    } catch (error) {
        console.error('PDF Generation Error:', error);
        res.status(500).json({ message: 'Failed to generate PDF report' });
    }
});

module.exports = router;
